### ISSUE TITLE
Testing PaymentIntents end-to-end non-interactively on the backend

### ISSUE THREAD

**Issue by sean-trustap** [stripe/sca-dev-chats#15] opened 2019-08-28 11:48 UTC
## Topic

I'm looking to run end-to-end backend tests on our transaction flows that use the new PaymentIntents API, but in a way that can be run non-interactively for CI. However, this is made difficult due to the new reliance on the JS SDK for the payment confirmation phase of the transaction (`stripe.handleCardPayment`), which requires a browser to complete successfully, and is thus a manual step in the process.

I have considered the following workarounds to the above issue:

* Run a full end-to-end test manually with a proxy that captures Stripe request/responses (e.g. http://www.mock-server.com/), then run tests against this proxy server during testing. This has the following problems, at least:

  * responses may potentially diverge from the actual Stripe API
  * tests would become very difficult to change
  * there would be extra overhead of running another server during CI, and the orchestration challenges that would come with it, as well as potential brittleness
  * unique PaymentIntent IDs would need to be generated to allow the webhooks to work correctly

* Use Selenium (or another mechanism for headless testing) to call `stripe.handleCardPayment`. This would be a large overhead onto our current backend-testing infrastructure (currently using Postman/`newman`), and I suspect it would be a fairly brittle step.

I have investigated the [Stripe CLI tool](https://github.com/stripe/stripe-cli) to see if I can continue the test by triggering `payment_intent.succeeded` events. However, these events seem to contain randomly generated data (as expected, because it doesn't take a payment intent parameter), including a randomly generated PaymentIntent ID - this means that it can't be used to look up and progress an existing transaction in our system. Furthermore, even if this worked, the PaymentIntent in Stripe presumably wouldn't have actually updated, so our view of the PaymentIntent would now be different to Stripe's view of the same PaymentIntent, which would cause later test failures when we, for example, try to perform a transfer using the charge associated with the successful payment.

I have also considered [confirm](https://stripe.com/docs/api/payment_intents/confirm)ing the PaymentIntent manually during testing in order to progress it, but my understanding is that this cannot be used with the automatic confirmation method that we are using.

An ideal solution to this problem for us would be for Stripe to provide a `POST /v1/payment_intents/:id/pay` endpoint that is only available in test mode. This would take a client secret and test payment details and (if those are valid) create the appropriate charge in the PaymentIntent as usual and fire webhooks as necessary. This would integrate into CI environments very easily and help make the transition to using PaymentIntents a lot smoother. Of course, I understand the major shortcoming of this approach in the fact that there is now a disparity between the production API and the test API, so I present it only as an example.

Any suggestions that could be made regarding this issue would be greatly appreciated.

## API

PaymentIntents

## Stripe Products

Connect

## Tech stack

- Backend language/frameworks: Go
- Frontend libraries/frameworks: Vue

**Comment by willock-stripe** [comment] 2019-09-11 12:37
Hi @sean-trustap –

Thank you for your question!

> I'm looking to run end-to-end backend tests on our transaction flows that use the new PaymentIntents API

I can absolutely understand the desire to run these kinds of integration tests wholly from your back-end – with the Charges API, this was possible, since there was no cardholder interaction required after the payment credentials are captured.

However, transactions that require 3D Secure inherently demand cardholder interaction. If you transition a `PaymentIntent` into `requires_action`, it will be in a terminal state unless you can fulfil that action. As you point out, a headless browser would unlock the ability to service the request, but this is only applicable to end-to-end integration tests.

I would encourage you to identify the types of tests you need for your Stripe integration, and determine which of them necessitate transitioning a `PaymentIntent` through a `requires_action` state. Off the top of my head:

**Feature specs, or end-to-end integration tests**: it absolutely makes sense in this instance to test a 3D Secure challenge, and in this type of test you will already have something Selenium-shaped in your test harness. In the case that our test-mode challenge changes, this would be immediately evident in your CI.

**Unit tests**: you're likely mocking out other third-party services in these sorts of tests already, but it's okay to hit Stripe in test-mode here. You might want to, for example, test capturing a `PaymentIntent` which is in the `requires_capture` status. In this case, this could be achieved with [one of the non-3D Secure test card numbers](https://stripe.com/docs/testing#cards), which can be sent direct-to-authorisation with an [immediately-confirmed `PaymentIntent`](https://stripe.com/docs/api/payment_intents/create#create_payment_intent-confirm), rather than by using [`handleCardPayment`](https://stripe.com/docs/stripe-js/reference#stripe-handle-card-payment).

I think the key thing to remember is that, inherently, a transaction that would require 3D Secure and a transaction that doesn't still transition through the same state machine. It's okay to take a `PaymentIntent` that's in `requires_confirmation` and "pretend" you already went through 3D Secure. That's the same state that a `PaymentIntent` ends up in after its 3D Secure challenge is completed anyway.

I can't think of any examples of a back-end unit test that would necessitate moving through a 3D Secure flow, but if you can provide some further food for thought I'd be happy to discuss this further!

**Closed** 2019-10-07 08:03 UTC
